-- ==========================================================
-- MIGRACIÓN: MÓDULO DE ACCESORIOS PARA DISFRACES / TRAJES
-- Permite gestionar accesorios independientes y piezas asociadas
-- ==========================================================

CREATE TABLE IF NOT EXISTS "ACCESORIOS" (
    "IDACCESORIO" SERIAL8 PRIMARY KEY,
    "CODBARRAS" VARCHAR(100) UNIQUE,
    "DESCRIPCION" VARCHAR(255) NOT NULL,
    "CATEGORIA" VARCHAR(100) DEFAULT 'GENERAL',
    "TALLA" VARCHAR(50) DEFAULT 'U',
    "STOCK" NUMERIC(10,2) DEFAULT 0,
    "VALOR" NUMERIC(14,2) DEFAULT 0,
    "VALORDEPOSITO" NUMERIC(14,2) DEFAULT 0,
    "IDARTICULO_PADRE" INT8,
    "NOTAS" TEXT,
    "ACTIVO" BOOLEAN DEFAULT TRUE,
    "FECHACREACION" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS "WDIDX_ACCESORIOS_CODBARRAS" ON "ACCESORIOS" ("CODBARRAS");
CREATE INDEX IF NOT EXISTS "WDIDX_ACCESORIOS_CATEGORIA" ON "ACCESORIOS" ("CATEGORIA");
CREATE INDEX IF NOT EXISTS "WDIDX_ACCESORIOS_PADRE" ON "ACCESORIOS" ("IDARTICULO_PADRE");

-- Asegurar columnas en CAMPOFACTURA para accesorios
DO $$ BEGIN
    ALTER TABLE "CAMPOFACTURA" ADD COLUMN IF NOT EXISTS "ES_ACCESORIO" BOOLEAN DEFAULT FALSE;
    ALTER TABLE "CAMPOFACTURA" ADD COLUMN IF NOT EXISTS "ID_TRAJE_PADRE" VARCHAR(100);
    ALTER TABLE "CAMPOFACTURA" ADD COLUMN IF NOT EXISTS "PIEZAS_INCLUIDAS" TEXT;
EXCEPTION
    WHEN OTHERS THEN NULL;
END $$;

-- Habilitar RLS y Políticas Permisivas
ALTER TABLE "ACCESORIOS" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS policy_full_access_ACCESORIOS ON "ACCESORIOS";
CREATE POLICY policy_full_access_ACCESORIOS ON "ACCESORIOS" 
FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

-- Permisos
GRANT USAGE ON SCHEMA public TO anon, authenticated, service_role;
GRANT ALL ON TABLE "ACCESORIOS" TO anon, authenticated, service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated, service_role;

-- Realtime
DO $$ BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE "ACCESORIOS";
EXCEPTION
    WHEN OTHERS THEN NULL;
END $$;
