-- ==========================================================
-- MIGRACIÓN DE REPARACIÓN DEFINITIVA Y PERMISOS DE PERSISTENCIA
-- Asegura que todas las ventas, abonos, clientes, artículos y
-- movimientos se guarden directamente en la base de datos Supabase
-- ==========================================================

-- 1. ELIMINAR CUALQUIER RESTRICCIÓN DE CLAVE FORÁNEA ERRÓNEA QUE BLOQUEE FACTURA
ALTER TABLE IF EXISTS "FACTURA" DROP CONSTRAINT IF EXISTS fk_factura_automatic;
ALTER TABLE IF EXISTS "FACTURA" DROP CONSTRAINT IF EXISTS "FACTURA_AUTOMATIC_fkey";
ALTER TABLE IF EXISTS "FACTURA1" DROP CONSTRAINT IF EXISTS fk_factura1_automatic;
ALTER TABLE IF EXISTS "FACTURA1" DROP CONSTRAINT IF EXISTS "FACTURA1_AUTOMATIC_fkey";

-- 2. ASEGURAR COLUMNAS COMPLETAS EN FACTURA
DO $$ BEGIN
    ALTER TABLE "FACTURA" ADD COLUMN IF NOT EXISTS "NUMEROFACT" VARCHAR(50);
    ALTER TABLE "FACTURA" ADD COLUMN IF NOT EXISTS "FECHASALIDA" VARCHAR(50);
    ALTER TABLE "FACTURA" ADD COLUMN IF NOT EXISTS "FECHAENTRADA" VARCHAR(50);
    ALTER TABLE "FACTURA" ADD COLUMN IF NOT EXISTS "FTOTALDEPOSITO" NUMERIC(14,2) DEFAULT 0;
    ALTER TABLE "FACTURA" ADD COLUMN IF NOT EXISTS "FTOTALVENTADEPOSITO" NUMERIC(14,2) DEFAULT 0;
    ALTER TABLE "FACTURA" ADD COLUMN IF NOT EXISTS "FORMAPAGO" VARCHAR(50) DEFAULT 'EFECTIVO';
    ALTER TABLE "FACTURA" ADD COLUMN IF NOT EXISTS "MODO" VARCHAR(50) DEFAULT 'ALQUILER';
    ALTER TABLE "FACTURA" ADD COLUMN IF NOT EXISTS "VENDEDOR" VARCHAR(100) DEFAULT 'ADMINISTRADOR';
    ALTER TABLE "FACTURA" ADD COLUMN IF NOT EXISTS "CCLIENTE" VARCHAR(200) DEFAULT 'GENERAL';
    ALTER TABLE "FACTURA" ADD COLUMN IF NOT EXISTS "CAMBIOS" NUMERIC(14,2) DEFAULT 0;
    ALTER TABLE "FACTURA" ADD COLUMN IF NOT EXISTS "PAGACON" NUMERIC(14,2) DEFAULT 0;
    ALTER TABLE "FACTURA" ADD COLUMN IF NOT EXISTS "ESTADOCLIENTE" VARCHAR(100) DEFAULT 'EN ALQUILER';
    ALTER TABLE "FACTURA" ADD COLUMN IF NOT EXISTS "CDIRECCION" VARCHAR(255) DEFAULT '';
    ALTER TABLE "FACTURA" ADD COLUMN IF NOT EXISTS "CTELEFONO" VARCHAR(50) DEFAULT '';
    ALTER TABLE "FACTURA" ADD COLUMN IF NOT EXISTS "CTELEFONO1" VARCHAR(50) DEFAULT '';
    ALTER TABLE "FACTURA" ADD COLUMN IF NOT EXISTS "CEMPRESA" VARCHAR(200) DEFAULT '';
    ALTER TABLE "FACTURA" ADD COLUMN IF NOT EXISTS "CCEDULA" VARCHAR(50) DEFAULT '';
    ALTER TABLE "FACTURA" ADD COLUMN IF NOT EXISTS "PAGOCONEFECTIVO" NUMERIC(14,2) DEFAULT 0;
    ALTER TABLE "FACTURA" ADD COLUMN IF NOT EXISTS "PAGOCONTRANFERENCIA" NUMERIC(14,2) DEFAULT 0;
    ALTER TABLE "FACTURA" ADD COLUMN IF NOT EXISTS "FTOTALALQUILER" NUMERIC(14,2) DEFAULT 0;
    ALTER TABLE "FACTURA" ADD COLUMN IF NOT EXISTS "FPAGOTRANS" VARCHAR(50) DEFAULT '';
    ALTER TABLE "FACTURA" ADD COLUMN IF NOT EXISTS "DESCUENTO" NUMERIC(14,2) DEFAULT 0;
    ALTER TABLE "FACTURA" ADD COLUMN IF NOT EXISTS "TOTAL_SALDO" NUMERIC(14,2) DEFAULT 0;
    ALTER TABLE "FACTURA" ADD COLUMN IF NOT EXISTS "FECHA_RECIBO" VARCHAR(50);
EXCEPTION
    WHEN OTHERS THEN NULL;
END $$;

-- 3. ASEGURAR COLUMNAS EN CAMPOFACTURA
DO $$ BEGIN
    ALTER TABLE "CAMPOFACTURA" ADD COLUMN IF NOT EXISTS "DESCRIPCION" VARCHAR(255);
    ALTER TABLE "CAMPOFACTURA" ADD COLUMN IF NOT EXISTS "CANTIDAD" NUMERIC(10,2) DEFAULT 1;
    ALTER TABLE "CAMPOFACTURA" ADD COLUMN IF NOT EXISTS "VALOR" NUMERIC(14,2) DEFAULT 0;
    ALTER TABLE "CAMPOFACTURA" ADD COLUMN IF NOT EXISTS "TOTAL" NUMERIC(14,2) DEFAULT 0;
    ALTER TABLE "CAMPOFACTURA" ADD COLUMN IF NOT EXISTS "BARRAS" VARCHAR(100) DEFAULT '';
    ALTER TABLE "CAMPOFACTURA" ADD COLUMN IF NOT EXISTS "NUMEROFACT" VARCHAR(50);
    ALTER TABLE "CAMPOFACTURA" ADD COLUMN IF NOT EXISTS "IDFACTURA" INT8;
    ALTER TABLE "CAMPOFACTURA" ADD COLUMN IF NOT EXISTS "VALORDEPOSITO" NUMERIC(14,2) DEFAULT 0;
    ALTER TABLE "CAMPOFACTURA" ADD COLUMN IF NOT EXISTS "TOTALALQUILER" NUMERIC(14,2) DEFAULT 0;
    ALTER TABLE "CAMPOFACTURA" ADD COLUMN IF NOT EXISTS "TOTALDEPOSITO" NUMERIC(14,2) DEFAULT 0;
EXCEPTION
    WHEN OTHERS THEN NULL;
END $$;

-- 4. ASEGURAR TABLAS SECUNDARIAS
CREATE TABLE IF NOT EXISTS "MOVIMIENTOS_INVENTARIO" (
    "IDMOVIMIENTO" SERIAL8 PRIMARY KEY,
    "FECHA" VARCHAR(100) DEFAULT CURRENT_TIMESTAMP::text,
    "IDARTICULO" INT8,
    "CODBARRAS" VARCHAR(100),
    "DESCRIPCION" VARCHAR(255),
    "TALLA" VARCHAR(50),
    "TIPO_MOVIMIENTO" VARCHAR(50),
    "CANTIDAD" NUMERIC(10,2) DEFAULT 0,
    "STOCK_ANTERIOR" NUMERIC(10,2) DEFAULT 0,
    "STOCK_NUEVO" NUMERIC(10,2) DEFAULT 0,
    "MOTIVO" VARCHAR(255),
    "USUARIO" VARCHAR(100),
    "NOTAS" TEXT
);

CREATE TABLE IF NOT EXISTS "EMPRESA_CONFIG" (
    "ID" SERIAL8 PRIMARY KEY,
    "NOMBRE_COMERCIAL" VARCHAR(200),
    "RAZON_SOCIAL" VARCHAR(200),
    "NIT" VARCHAR(50),
    "DIRECCION" VARCHAR(255),
    "CIUDAD" VARCHAR(100),
    "TELEFONO1" VARCHAR(50),
    "TELEFONO2" VARCHAR(50),
    "EMAIL" VARCHAR(100),
    "REGIMEN" VARCHAR(100),
    "MENSAJE_PIE" TEXT,
    "TERMINOS" TEXT,
    "LOGO_URL" TEXT,
    "MONEDA" VARCHAR(10) DEFAULT 'COP',
    "SIMBOLO_MONEDA" VARCHAR(5) DEFAULT '$',
    "DIAS_ALQUILER" NUMERIC(5,0) DEFAULT 3
);

-- 5. HABILITAR RLS Y CREAR POLÍTICAS PERMISIVAS PARA ACCESO COMPLETO (ANON Y AUTHENTICATED)
DO $$ 
DECLARE
    tbl text;
    tables text[] := ARRAY[
        'FACTURA',
        'CAMPOFACTURA',
        'CLIENTES',
        'ARTICULO',
        'CAJAS',
        'ABONO_CLIENTE',
        'DEPOSITOENTREGADO',
        'depositoentregado',
        'gastos',
        'GASTOS',
        'MOVIMIENTOS_INVENTARIO',
        'EMPRESA_CONFIG',
        'LOGIN',
        'FACTURA1',
        'CAMPOFACTURA1',
        'clientesregistrados',
        'numero_de_serie'
    ];
BEGIN
    FOREACH tbl IN ARRAY tables LOOP
        -- Verificar si la tabla existe antes de configurar RLS
        IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = tbl AND table_schema = 'public') THEN
            EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY;', tbl);
            
            -- Eliminar política anterior si existiera
            EXECUTE format('DROP POLICY IF EXISTS %I ON %I;', 'policy_full_access_' || tbl, tbl);
            
            -- Crear política permisiva para SELECT, INSERT, UPDATE, DELETE
            EXECUTE format('CREATE POLICY %I ON %I FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);', 'policy_full_access_' || tbl, tbl);
        END IF;
    END LOOP;
END $$;

-- 6. PERMISOS Y PRIVILEGIOS DE ESQUEMA Y TABLAS
GRANT USAGE ON SCHEMA public TO anon, authenticated, service_role;
GRANT ALL ON ALL TABLES IN SCHEMA public TO anon, authenticated, service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated, service_role;
GRANT ALL ON ALL ROUTINES IN SCHEMA public TO anon, authenticated, service_role;

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON ROUTINES TO anon, authenticated, service_role;
