-- ==============================================================================
-- BASE DE DATOS PRINCIPAL: CLIENTES.wda (WINDEV / PostgreSQL)
-- Script generado para PostgreSQL / Supabase
-- ==============================================================================

-- 1. EXTENSIONES
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- Creación de la tabla numero_de_serie
CREATE TABLE IF NOT EXISTS "numero_de_serie" (
    "IDnumero_de_serie" SERIAL8 PRIMARY KEY,
    "SERIE" VARCHAR(50) UNIQUE
);

-- Creación de la tabla clientesregistrados
CREATE TABLE IF NOT EXISTS "clientesregistrados" (
    "IDEmpresa" SERIAL8 PRIMARY KEY,
    "RAZOSOCIAL" VARCHAR(50),
    "ENOMBRE" VARCHAR(50),
    "NIT" VARCHAR(50),
    "ETIPO" VARCHAR(50),
    "EDIRECCION" VARCHAR(50),
    "ETELEFONO" VARCHAR(50) DEFAULT '0',
    "EMAIL" VARCHAR(50),
    "WEB" VARCHAR(50),
    "SERIE" VARCHAR(50) UNIQUE,
    "LOGO" BYTEA,
    "IDnumero_de_serie" BIGINT DEFAULT 0,
    "MENSAJE" VARCHAR(50)
);
CREATE INDEX IF NOT EXISTS "WDIDX_clientesregistrados_IDnumero_de_serie" ON "clientesregistrados" ("IDnumero_de_serie");

-- Creación de la tabla Empresa
CREATE TABLE IF NOT EXISTS "Empresa" (
    "IDEmpresa" SERIAL8 PRIMARY KEY,
    "RAZOSOCIAL" VARCHAR(50),
    "ENOMBRE" VARCHAR(50),
    "NIT" VARCHAR(50),
    "ETIPO" VARCHAR(50),
    "EDIRECCION" VARCHAR(50),
    "ETELEFONO" VARCHAR(50) DEFAULT '0',
    "EMAIL" VARCHAR(50),
    "WEB" VARCHAR(50),
    "SERIE" VARCHAR(50),
    "LOGO" BYTEA,
    "MENSAJE" VARCHAR(50)
);

-- Creación de la tabla CAJAS
CREATE TABLE IF NOT EXISTS "CAJAS" (
    "IDCAJAS" SERIAL8 PRIMARY KEY,
    "NOMBRECAJA" VARCHAR(50) UNIQUE,
    "RESOLUCION" VARCHAR(50),
    "NUMERACION" INTEGER DEFAULT 0,
    "PREFIJO" VARCHAR(50)
);

-- Creación de la tabla CLIENTES
CREATE TABLE IF NOT EXISTS "CLIENTES" (
    "IDCLIENTES" SERIAL8 PRIMARY KEY,
    "CEDULA" BIGINT DEFAULT 0,
    "DIRECCION" VARCHAR(50),
    "TELEFONO" VARCHAR(50) DEFAULT '0',
    "TELEFONO2" VARCHAR(50),
    "EMPRESA" VARCHAR(50),
    "DIRECCIONEMP" VARCHAR(50),
    "NOMBRE" VARCHAR(50),
    "SALDO" INTEGER DEFAULT 0,
    "NOTA" VARCHAR(2000)
);
CREATE INDEX IF NOT EXISTS "WDIDX_CLIENTES_CEDULA" ON "CLIENTES" ("CEDULA");
CREATE INDEX IF NOT EXISTS "WDIDX_CLIENTES_DIRECCION" ON "CLIENTES" ("DIRECCION");
CREATE INDEX IF NOT EXISTS "WDIDX_CLIENTES_TELEFONO" ON "CLIENTES" ("TELEFONO");
CREATE INDEX IF NOT EXISTS "WDIDX_CLIENTES_TELEFONO2" ON "CLIENTES" ("TELEFONO2");
CREATE INDEX IF NOT EXISTS "WDIDX_CLIENTES_EMPRESA" ON "CLIENTES" ("EMPRESA");
CREATE INDEX IF NOT EXISTS "WDIDX_CLIENTES_DIRECCIONEMP" ON "CLIENTES" ("DIRECCIONEMP");
CREATE INDEX IF NOT EXISTS "WDIDX_CLIENTES_NOMBRE" ON "CLIENTES" ("NOMBRE");
CREATE INDEX IF NOT EXISTS "WDIDX_CLIENTES_SALDO" ON "CLIENTES" ("SALDO");

-- Creación de la tabla ESTADO_CLI
CREATE TABLE IF NOT EXISTS "ESTADO_CLI" (
    "IDESTADO_CLI" SERIAL8 PRIMARY KEY,
    "ESTADOCLI" VARCHAR(50) NOT NULL DEFAULT '0'
);

-- Creación de la tabla ESTADO_TRAJE
CREATE TABLE IF NOT EXISTS "ESTADO_TRAJE" (
    "IDESTADO_TRAJE" SERIAL8 PRIMARY KEY,
    "ESTADO_TRAJE" SMALLINT DEFAULT 0
);

-- Creación de la tabla F_PAGO
CREATE TABLE IF NOT EXISTS "F_PAGO" (
    "FDEPAGO" VARCHAR(50) DEFAULT '0',
    "IDESTADCLI" SERIAL8 PRIMARY KEY
);

-- Creación de la tabla OTRAS_F_PAGO
CREATE TABLE IF NOT EXISTS "OTRAS_F_PAGO" (
    "IDOTRA_F_PAGO" SERIAL8 PRIMARY KEY,
    "OTRAS_F_PAGO" VARCHAR(50)
);

-- Creación de la tabla contraseñas
CREATE TABLE IF NOT EXISTS "contraseñas" (
    "IDcontraseñas" SERIAL8 PRIMARY KEY,
    "BORRADO" VARCHAR(50) DEFAULT '0',
    "CONFIGURACIONES" VARCHAR(50) DEFAULT '0',
    "PERMISOS" VARCHAR(50) DEFAULT '0'
);
CREATE INDEX IF NOT EXISTS "WDIDX_contraseñas_BORRADO" ON "contraseñas" ("BORRADO");
CREATE INDEX IF NOT EXISTS "WDIDX_contraseñas_CONFIGURACIONES" ON "contraseñas" ("CONFIGURACIONES");
CREATE INDEX IF NOT EXISTS "WDIDX_contraseñas_PERMISOS" ON "contraseñas" ("PERMISOS");

-- Creación de la tabla LOGIN
CREATE TABLE IF NOT EXISTS "LOGIN" (
    "IDLOGIN" SERIAL8 PRIMARY KEY,
    "INOMBRE" VARCHAR(50),
    "IAPELLIDO" VARCHAR(50),
    "ILOGIN" INTEGER UNIQUE DEFAULT 0,
    "PASSWORD" VARCHAR(50),
    "TIPO" BOOL DEFAULT false,
    "ACCESOALMENU" BOOL DEFAULT false
);

-- Creación de la tabla gastos
CREATE TABLE IF NOT EXISTS "gastos" (
    "IDgastos" SERIAL8 PRIMARY KEY,
    "DESCRIPCIONSALIDA" VARCHAR(50),
    "FECHA" DATE,
    "VALORSALIDA" VARCHAR(50),
    "NUMEROGASTO" VARCHAR(50) UNIQUE
);

-- Creación de la tabla CAMPOFACTURA
CREATE TABLE IF NOT EXISTS "CAMPOFACTURA" (
    "AUTOMATIC" SERIAL8 PRIMARY KEY,
    "DESCRIPCION" VARCHAR(300),
    "CANTIDAD" NUMERIC(24,6) DEFAULT 0,
    "VALOR" NUMERIC(24,6) DEFAULT 0,
    "TOTAL" NUMERIC(24,6) DEFAULT 0,
    "BARRAS" VARCHAR(50) DEFAULT '0',
    "NUMEROFACT" VARCHAR(50),
    "IDFACTURA" BIGINT DEFAULT 0,
    "VALORDEPOSITO" NUMERIC(24,6) DEFAULT 0,
    "TOTALALQUILER" NUMERIC(24,6) DEFAULT 0,
    "TOTALDEPOSITO" NUMERIC(24,6) DEFAULT 0
);
CREATE INDEX IF NOT EXISTS "WDIDX_CAMPOFACTURA_IDFACTURA" ON "CAMPOFACTURA" ("IDFACTURA");

-- Creación de la tabla ARTICULO
CREATE TABLE IF NOT EXISTS "ARTICULO" (
    "IDARTICULO" SERIAL8 PRIMARY KEY,
    "DESCRIPCION" VARCHAR(150),
    "TALLA" VARCHAR(50),
    "STOCK" INTEGER DEFAULT 0,
    "VALOR" NUMERIC(24,6) DEFAULT 0,
    "CODBARRAS" VARCHAR(50),
    "IDCAMPOFACTURA" BIGINT DEFAULT 0,
    "VALORDEPOSITO" NUMERIC(24,6) DEFAULT 0
);
CREATE INDEX IF NOT EXISTS "WDIDX_ARTICULO_DESCRIPCION" ON "ARTICULO" ("DESCRIPCION");
CREATE INDEX IF NOT EXISTS "WDIDX_ARTICULO_TALLA" ON "ARTICULO" ("TALLA");
CREATE INDEX IF NOT EXISTS "WDIDX_ARTICULO_STOCK" ON "ARTICULO" ("STOCK");
CREATE INDEX IF NOT EXISTS "WDIDX_ARTICULO_VALOR" ON "ARTICULO" ("VALOR");
CREATE INDEX IF NOT EXISTS "WDIDX_ARTICULO_CODBARRAS" ON "ARTICULO" ("CODBARRAS");
CREATE INDEX IF NOT EXISTS "WDIDX_ARTICULO_IDCAMPOFACTURA" ON "ARTICULO" ("IDCAMPOFACTURA");
CREATE INDEX IF NOT EXISTS "WDIDX_ARTICULO_VALORDEPOSITO" ON "ARTICULO" ("VALORDEPOSITO");

-- Creación de la tabla FACTURA
CREATE TABLE IF NOT EXISTS "FACTURA" (
    "IDFACTURA" SERIAL8 PRIMARY KEY,
    "NUMEROFACT" VARCHAR(50) UNIQUE DEFAULT '0',
    "FECHASALIDA" DATE,
    "FECHAENTRADA" DATE,
    "FTOTALDEPOSITO" NUMERIC(24,6) DEFAULT 0,
    "FTOTALVENTADEPOSITO" NUMERIC(24,6) DEFAULT 0,
    "FORMAPAGO" VARCHAR(50) DEFAULT '0',
    "MODO" VARCHAR(50),
    "VENDEDOR" VARCHAR(50),
    "CCLIENTE" VARCHAR(50),
    "CAMBIOS" NUMERIC(24,6) DEFAULT 0,
    "PAGACON" NUMERIC(24,6) DEFAULT 0,
    "AUTOMATIC" BIGINT DEFAULT 0,
    "IDFCLIENTES" BIGINT DEFAULT 0,
    "ESTADOCLIENTE" VARCHAR(50) DEFAULT '0',
    "IDF_PAGO" BIGINT DEFAULT 0,
    "CDIRECCION" VARCHAR(50),
    "CTELEFONO" VARCHAR(50),
    "CTELEFONO1" VARCHAR(50),
    "CEMPRESA" VARCHAR(50),
    "CCEDULA" VARCHAR(50),
    "GASTOS" VARCHAR(50),
    "PAGOCONEFECTIVO" NUMERIC(24,6) DEFAULT 0,
    "PAGOCONTRANFERENCIA" NUMERIC(24,6) DEFAULT 0,
    "FTOTALALQUILER" NUMERIC(24,6) DEFAULT 0,
    "FPAGOTRANS" VARCHAR(50),
    "DESCUENTO" NUMERIC(24,6) DEFAULT 0,
    "P_SALDO_EFECTIVO" NUMERIC(24,6) DEFAULT 0,
    "P_SALDO_TRANFERENCIA" NUMERIC(24,6) DEFAULT 0,
    "TOTAL_SALDO" NUMERIC(24,6) DEFAULT 0,
    "FECHA_RECIBO" DATE,
    "SALDOA_BONADO" NUMERIC(24,6) DEFAULT 0,
    "FECHAINGRESO" DATE
);
CREATE INDEX IF NOT EXISTS "WDIDX_FACTURA_FORMAPAGO" ON "FACTURA" ("FORMAPAGO");
CREATE INDEX IF NOT EXISTS "WDIDX_FACTURA_CCLIENTE" ON "FACTURA" ("CCLIENTE");
CREATE INDEX IF NOT EXISTS "WDIDX_FACTURA_AUTOMATIC" ON "FACTURA" ("AUTOMATIC");
CREATE INDEX IF NOT EXISTS "WDIDX_FACTURA_IDFCLIENTES" ON "FACTURA" ("IDFCLIENTES");
CREATE INDEX IF NOT EXISTS "WDIDX_FACTURA_ESTADOCLIENTE" ON "FACTURA" ("ESTADOCLIENTE");
CREATE INDEX IF NOT EXISTS "WDIDX_FACTURA_IDF_PAGO" ON "FACTURA" ("IDF_PAGO");
CREATE INDEX IF NOT EXISTS "WDIDX_FACTURA_CCEDULA" ON "FACTURA" ("CCEDULA");

-- Creación de la tabla FACTURA1
CREATE TABLE IF NOT EXISTS "FACTURA1" (
    "IDFACTURA" SERIAL8 PRIMARY KEY,
    "NUMEROFACT" VARCHAR(50) UNIQUE DEFAULT '0',
    "FECHASALIDA" DATE,
    "FECHAENTRADA" DATE,
    "FTOTALDEPOSITO" NUMERIC(24,6) DEFAULT 0,
    "FTOTALVENTADEPOSITO" NUMERIC(24,6) DEFAULT 0,
    "FORMAPAGO" VARCHAR(50) DEFAULT '0',
    "MODO" VARCHAR(50),
    "VENDEDOR" VARCHAR(50),
    "CCLIENTE" VARCHAR(50),
    "CAMBIOS" NUMERIC(24,6) DEFAULT 0,
    "PAGACON" NUMERIC(24,6) DEFAULT 0,
    "AUTOMATIC" BIGINT DEFAULT 0,
    "IDFCLIENTES" BIGINT DEFAULT 0,
    "ESTADOCLIENTE" VARCHAR(50) DEFAULT '0',
    "IDF_PAGO" BIGINT DEFAULT 0,
    "CDIRECCION" VARCHAR(50),
    "CTELEFONO" VARCHAR(50),
    "CTELEFONO1" VARCHAR(50),
    "CEMPRESA" VARCHAR(50),
    "CCEDULA" VARCHAR(50),
    "GASTOS" VARCHAR(50),
    "PAGOCONEFECTIVO" NUMERIC(24,6) DEFAULT 0,
    "PAGOCONTRANFERENCIA" NUMERIC(24,6) DEFAULT 0,
    "FTOTALALQUILER" NUMERIC(24,6) DEFAULT 0,
    "FPAGOTRANS" VARCHAR(50),
    "DESCUENTO" NUMERIC(24,6) DEFAULT 0
);
CREATE INDEX IF NOT EXISTS "WDIDX_FACTURA1_FORMAPAGO" ON "FACTURA1" ("FORMAPAGO");
CREATE INDEX IF NOT EXISTS "WDIDX_FACTURA1_CCLIENTE" ON "FACTURA1" ("CCLIENTE");
CREATE INDEX IF NOT EXISTS "WDIDX_FACTURA1_AUTOMATIC" ON "FACTURA1" ("AUTOMATIC");
CREATE INDEX IF NOT EXISTS "WDIDX_FACTURA1_IDFCLIENTES" ON "FACTURA1" ("IDFCLIENTES");
CREATE INDEX IF NOT EXISTS "WDIDX_FACTURA1_ESTADOCLIENTE" ON "FACTURA1" ("ESTADOCLIENTE");
CREATE INDEX IF NOT EXISTS "WDIDX_FACTURA1_IDF_PAGO" ON "FACTURA1" ("IDF_PAGO");
CREATE INDEX IF NOT EXISTS "WDIDX_FACTURA1_CCEDULA" ON "FACTURA1" ("CCEDULA");

-- Creación de la tabla ABONO_CLIENTE
CREATE TABLE IF NOT EXISTS "ABONO_CLIENTE" (
    "IDABONO_CLIENTE" SERIAL8 PRIMARY KEY,
    "NUMEROABONO" VARCHAR(50),
    "ACLIENTE" VARCHAR(50),
    "AFACTURA" VARCHAR(50),
    "PAGOEFECTIVO" NUMERIC(24,6) DEFAULT 0,
    "PAGOTRANFE" NUMERIC(24,6) DEFAULT 0,
    "FECHAABONO" DATE,
    "SALDOANTERIOR" NUMERIC(24,6) DEFAULT 0,
    "SALDODEBER" NUMERIC(24,6) DEFAULT 0,
    "TOTAL_ABONO" NUMERIC(24,6) DEFAULT 0
);

-- Creación de la tabla depositoentregado
CREATE TABLE IF NOT EXISTS "depositoentregado" (
    "IDdepositoentregado" SERIAL8 PRIMARY KEY,
    "NUMEROFACTURA" VARCHAR(50),
    "VALOR" INTEGER DEFAULT 0,
    "FECHA" DATE
);

-- Creación de la tabla TRANSACCIONES
CREATE TABLE IF NOT EXISTS "TRANSACCIONES" (
    "IDTRANSACCIONES" SERIAL8 PRIMARY KEY,
    "TRANSACCIONES_BUSCAR" TEXT NOT NULL,
    "TRANSACCIONES_Tabla_FACTURA_IDFACTURA" INTEGER NOT NULL DEFAULT 0,
    "TRANSACCIONES_Tabla_FACTURA_NUMEROFACT" TEXT NOT NULL,
    "TRANSACCIONES_Tabla_FACTURA_FECHASALIDA" DATE NOT NULL,
    "TRANSACCIONES_Tabla_FACTURA_FECHAENTRADA" DATE NOT NULL,
    "TRANSACCIONES_Tabla_FACTURA_SUBTOTAL" NUMERIC(24,6) NOT NULL DEFAULT 0,
    "TRANSACCIONES_Tabla_FACTURA_TOTALVENTA" NUMERIC(24,6) NOT NULL DEFAULT 0,
    "TRANSACCIONES_Tabla_FACTURA_FORMAPAGO" INTEGER NOT NULL DEFAULT 0,
    "TRANSACCIONES_Tabla_FACTURA_MODO" VARCHAR(50) NOT NULL,
    "TRANSACCIONES_Tabla_FACTURA_VENDEDOR" VARCHAR(50) NOT NULL,
    "TRANSACCIONES_Tabla_FACTURA_CCLIENTE" VARCHAR(50) NOT NULL
);

-- RESTRICCIONES DE INTEGRIDAD
DO $$ BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints 
        WHERE constraint_name = 'fk_clientesregistrados_serie'
    ) THEN
        ALTER TABLE "clientesregistrados" 
        ADD CONSTRAINT fk_clientesregistrados_serie 
        FOREIGN KEY ("IDnumero_de_serie") REFERENCES "numero_de_serie" ("IDnumero_de_serie");
    END IF;
EXCEPTION
    WHEN duplicate_object THEN NULL;
    WHEN foreign_key_violation THEN NULL;
    WHEN others THEN NULL;
END $$;

DO $$ BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints 
        WHERE constraint_name = 'fk_factura_automatic'
    ) THEN
        ALTER TABLE "FACTURA" 
        ADD CONSTRAINT fk_factura_automatic 
        FOREIGN KEY ("AUTOMATIC") REFERENCES "CAMPOFACTURA" ("AUTOMATIC");
    END IF;
EXCEPTION
    WHEN duplicate_object THEN NULL;
    WHEN foreign_key_violation THEN NULL;
    WHEN others THEN NULL;
END $$;

-- PERMISOS Y GRANTS PARA SUPABASE (anon y authenticated)
GRANT USAGE ON SCHEMA public TO anon, authenticated;
GRANT ALL ON ALL TABLES IN SCHEMA public TO anon, authenticated;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated;
