-- Migración para ampliar los límites de caracteres en FACTURA, CAMPOFACTURA y CLIENTES
-- Previene el error PostgreSQL 22001 (value too long for type character varying(50))

ALTER TABLE "FACTURA" 
  ALTER COLUMN "CCLIENTE" TYPE VARCHAR(255),
  ALTER COLUMN "CDIRECCION" TYPE VARCHAR(255),
  ALTER COLUMN "CEMPRESA" TYPE VARCHAR(255),
  ALTER COLUMN "FPAGOTRANS" TYPE VARCHAR(255),
  ALTER COLUMN "GASTOS" TYPE VARCHAR(255),
  ALTER COLUMN "VENDEDOR" TYPE VARCHAR(100),
  ALTER COLUMN "MODO" TYPE VARCHAR(100),
  ALTER COLUMN "FORMAPAGO" TYPE VARCHAR(100),
  ALTER COLUMN "ESTADOCLIENTE" TYPE VARCHAR(100);

ALTER TABLE "CAMPOFACTURA"
  ALTER COLUMN "DESCRIPCION" TYPE VARCHAR(500),
  ALTER COLUMN "PIEZAS_INCLUIDAS" TYPE VARCHAR(1000);

ALTER TABLE "CLIENTES"
  ALTER COLUMN "NOMBRE" TYPE VARCHAR(255),
  ALTER COLUMN "DIRECCION" TYPE VARCHAR(255),
  ALTER COLUMN "DIRECCIONEMP" TYPE VARCHAR(255),
  ALTER COLUMN "EMPRESA" TYPE VARCHAR(255);
